djangfile/neptune/books/urls.py
from django.urls import path
from . import views

app_name = "books"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:author_id>/", views.author, name="author"),
    path("<int:author_id>/<int:book_id>", views.book, name="book"),
    path("genre/<int:genre_id>", views.genre, name="genre")
]

djangfile/neptune/neptune/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("books/", include("books.urls")),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

djangfile/neptune/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

djangfile/neptune/books/models.py
from django.db import models
import datetime
from django.utils import timezone


class Author(models.Model):
    author_name = models.CharField(max_length=200)
    birthday = models.DateField()
    nationality = models.CharField(max_length=200)

    def __str__(self):
        return self.author_name


class Genre(models.Model):
    genre_name = models.CharField(max_length=200)

    def __str__(self):
        return self.genre_name

# Create your models here.


class Book(models.Model):
    book_title = models.CharField(max_length=200)
    pub_date = models.DateField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

    def __str__(self):
        return self.book_title

djangfile/neptune/polls/models.py
from django.utils import timezone
from django.db import models
import datetime

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

djangfile/neptune/books/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
from .models import Book, Author

def index(request):
    random_books = Book.objects.all()[:5]
    context = {"random_books": random_books}
    return render(request, "books/index.html", context)

def book(request, author_id, book_id):
    book = Book.objects.get(pk=book_id)
    context = {"book":book}
    return render(request, "books/book.html", context)

def author(request, author_id):
    author = Author.objects.get(pk=author_id)
    author_books = Book.objects.filter(author=author)
    context = {"author":author, "author_books":author_books}
    return render(request, "books/author.html", context)

def genre(request, genre_id):
    return HttpResponse("Genre")

djangfile/neptune/polls/views.py
from .models import Question, Choice
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# Create your views here.

djangfile/neptune/books/templates/books/author.html
{% if author %}
    <h1>{{author.author_name}}</h1>
<ul>
    {% for i in author_books %}
    <li> <a href="{% url 'books:book' author.id i.id %}">{{i.book_title}}</a> </li>
    {% endfor %}
</ul>
<ul> <a href="{% url "books:index" %}">RETURN</a> </ul>
{% endif %}

djangfile/neptune/books/templates/books/book.html
{% if book %}
    <h1>{{book.book_title}}</h1>
    <ul> <a href="{% url "books:author" book.author.id %}">{{book.author.author_name}}</a> </ul>
    <ul> <a href="{% url "books:index" %}">RETURN</a> </ul>
{% endif %}

djangfile/neptune/books/templates/books/index.html
{% if random_books %}
    <ul>
    {% for book in random_books %}
        <li><a href="{{book.author.id}}/{{book.id}}">{{book.book_title}} - {{book.author.author_name}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No books are available.</p>
{% endif %}

djangfile/neptune/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

djangfile/neptune/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css'%}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

djangfile/neptune/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>